apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  #storageclass.kubernetes.io/is-default-class: "true"
  name: gp3-expansion
parameters:
  fsType: ext4
  type: gp3
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
