apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx1
  name: hostpath-2
spec:
  containers:
  - image: nginx
    name: mynginx1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host-example
      mountPath: /home/devops
  volumes:
  - name: host-example
    hostPath:
      path: /mnt/devops
      type: Directory
