apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-hard-not-matching
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - web
  containers:
  - name: with-node-affinity
    image: httpd

