apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-soft-3
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: type
            operator: In
            values:
            - web
            - frontend
  containers:
  - name: with-node-affinity
    image: httpd
