apiVersion: v1
kind: Pod
metadata:
  name: nginx-label-demo-anti
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: env
            operator: NotIn
            values:
            - test
        topologyKey: kubernetes.io/hostname

