apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx1
  name: mynginx-cpu-mem
spec:
  containers:
  - image: nginx
    name: mynginx
    resources:
      requests:
        cpu: "20m"
        memory: "50Mi"
      limits:
        cpu: "50m"
        memory: "100Mi"
