apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx1
  name: mynginx-cpu-mem-1
spec:
  containers:
  - image: nginx
    name: mynginx
    resources:
      requests:
        cpu: "2000m"
        memory: "5Gi"
      limits:
        cpu: "2000m"
        memory: "5Gi"
