apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration-equal-noexecute
  labels:
    env: taint-toleration-1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "app"
    effect: "NoExecute"
  nodeSelector:
    type: web
