apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-grafana-rediness-fail
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:main-ubuntu
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 300Mi
        readinessProbe:
          httpGet:
            path: /
            port: 3001


