apiVersion: apps/v1
kind: Deployment
metadata:
   name: deploy-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pod 
  template:
    metadata:
      labels:
        run: pod
    spec:
      containers:
      - image: httpd
        name: pod
        volumeMounts:
        - name: test-config
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf 
      volumes:
      - name: test-config
        configMap:
          name: my-config
